version: '3'
services:
  web:
    build: .
    restart: always
    network_mode: bridge
    links:
      - db
    ports:
      - 8088:8088
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: bridge
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: WebService
    ports:
      - 3308:3308